### ISSUE TITLE
BUG - Inject not work for projects stored on iCloud Drive

### ISSUE THREAD

**Issue by maartinj** [krzysztofzablocki/Inject#101]
## Describe the bug
* Xcode projects stored on iCloud Drive not work with Inject package. Xcode projects stored, for example, on Desktop, works correctly, but on iCloud Drive not. No matter whether Xcode project is small or big. I tested on fresh Xcode project created directly from Xcode and this even not work if it is stored on iCloud Drive.

## To Reproduce
1. Add SPM via Xcode
2. Add "-Xlinker -interposable" (without the double quotes and on separate lines) to the "Other Linker Flags"
3. Download newest version of Xcode Injection
4. Unpack it and place under /Applications
5. Xcode version to compile i under the default location: /Applications/Xcode.app
6. Run the injection application
7. Select open project / open recent from it's menu and pick the right workspace file stored on iCloud Drive
8. Add `import Inject`
9. Add `.enableInjection()` at the end of body definition
10. Add `@ObserveInjection var inject` to view struct
11. Run Xcode project
12. Change something in the view of Xcode project (for example, Text("Hello World") to Text("Hello)")
13. Click Cmd + S
14. See erros in debug console

## Expected behavior
* Inject will work for projects stored on iCloud Drive

## Screenshots
<img src="https://github.com/user-attachments/assets/5fc8b51e-2fbf-4ad1-bbfd-951610ec1411" height="250">

>💉 ⚠️ Could not locate compile command for "/Users/marcinjedrzejak/Library/Mobile Documents/com~apple~CloudDocs/Developer/AquaVibe/AquaVibe/Screens/Settings/SettingsView.swift" in /Users/marcinjedrzejak/Library/Developer/Xcode/DerivedData/AquaVibe-cajjtsrvofweaaavplnnhceixeel/Logs/Build/.
>This could be due to one of the following:
>1. Injection does not work with Whole Module Optimization.
>2. There are restrictions on characters allowed in paths.
>3. File paths in the simulator are case sensitive.
>4. The modified source file is not in the current project.
>5. The source file is an XCTest that has not been run yet.
>6. Xcode has removed the build logs. Edit a file and re-run
or try a build clean then rebuild to make logs available or
consult: "/Users/marcinjedrzejak/Library/Developer/CoreSimulator/Devices/A10C3F60-4DDF-4F05-A94D-0CE117259F24/data/Containers/Data/Application/73D59922-9FDF-4851-83A8-D22F4EED875A/tmp/command.sh". Whatever the problem, if you see
this error it may be worth trying the new implementation
https://github.com/johnno1962/InjectionNext.

## Device Info:
 * Device: iPhone 16 Pro Simulator
 * OS: iOS 18.0

**Comment by johnno1962** [comment]
Did you try the new implementation as it suggests? When you encounter this problem that is probably your best option if you don't want to move the project out of iCloud Drive.

**Comment by maartinj** [comment]
Not fully, in new project from scratch, it works until I change something, for example, with button, then is below error in console. In my other project, I immediately had below error:

🔥 ⚠️ Symbols altered, this may not be supported. 256 c.f. 256

**Comment by johnno1962** [comment]
That error is a warning as the numbers are the same, I'll change the emoji. Other than that is it working?

**Comment by maartinj** [comment]
View is not updated even console is showing that changes has been done.

Cmd + S, console shows something done in the background, but view in simulator is not refreshed:

<img width="1162" alt="issue2" src="https://github.com/user-attachments/assets/e6b58bfa-971f-47fc-bbd8-2f99d1f71811">

**Comment by johnno1962** [comment]
Bu do you have a `@ObserveInjection var redraw` inside that particular view?

**Comment by maartinj** [comment]
I spotted where was issue, apologies, never mind. 'Prepare SwiftUI' option from InjectionNext app assigned the codes to wrong sections. Now looks that is working fine 👍

For summary, for projects stored in local drive, I should use Inject? For projects stored in iCloud Drive, I should use InjectionNext?

**Comment by johnno1962** [comment]
`InjectionIII` and `InjectionNext` are alternative substrates that operate under and implement `Inject`. You would always use `Inject` and you can use the newer `InjectionNext` when the project is on iCloud Drive or either otherwise.
