### ISSUE TITLE
Injection may have failed.

### ISSUE THREAD

**Issue by JakfarShodiq** [krzysztofzablocki/Inject#102]
I already added -Xlinker -interposable to the "Other Linker Flags" but still can't.
I use code Version 16.0, any feedbacks?
![Screenshot 2024-10-23 at 17 17 24](https://github.com/user-attachments/assets/32f5a4e6-7f79-46be-af48-27ecf6704f4c)

**Comment by johnno1962** [comment]
Which version of InjectionIII app is this. For Xcode.16 it needs to be 5.0.1 or above downloaded from this repo.

**Comment by JakfarShodiq** [comment]
> Which version of InjectionIII app is this. For Xcode.16 it needs to be 5.0.1 or above downloaded from [this repo](https://github.com/johnno1962/InjectionIII/releases).

Hi @johnno1962 thank you, it's working. Awesome!
