### ISSUE TITLE
Unable to Archive app 

### ISSUE THREAD

**Issue by teameh** [krzysztofzablocki/Inject#103]
Building, running, testing all works like a charm, but I'm unable to Archive my app when inject is included as a package. 

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip:1:1: 
symbols referenced by indirect symbol table entries that can't be stripped in: 
/Users/Teameh/Developer/Apps/MyApp/DerivedData/MyApp/Build/Intermediates.noindex/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app/MyApp
```

Using the new Xcode 16.1 (16B40) RC

**Comment by krzysztofzablocki** [comment]
Inject in release build is basically empty and there is thousands of apps using it daily in prod so this seems unlikely to be Inject related and more likely some cache / setting issue

**Comment by teameh** [comment]
Yeah my thoughts exactly, I thought it would maybe be Xcode 16.1 related.. but I'll close this for now. At least this is issue is up here now. If somebody reads this knowing the solution, please let me know 😄

**Comment by metinaltinbas** [comment]
Having the same problem and couldn't find a problem, I am using xCode 16.1

**Comment by johnno1962** [comment]
Are you sure the -Xlinker -interposable "Other Linker Flag" is added for Debug build only?

**Comment by teameh** [comment]
Nope. That was it! Thanks so much for looking into this for us. PR to make this more clear https://github.com/krzysztofzablocki/Inject/pull/106

**Comment by metinaltinbas** [comment]
> Are you sure the -Xlinker -interposable "Other Linker Flag" is added for Debug build only?

Thank you, it wasn't. My bad

**Comment by phgn0** [comment]
Same here! I got this message when uploading the app build:

```
Asset validation failed
The app contains one or more corrupted binaries. ...
```

Which got fixed after only setting the linker flags for debug builds.

(commenting here so other people find this)

**Comment by justFI** [comment]
just do this right, it will fixed!
<img width="560" height="183" alt="Image" src="https://github.com/user-attachments/assets/51e20fae-a3e4-4374-b643-e28d942b636e" />
