### ISSUE TITLE
Older Swift Tool Version Support

### ISSUE THREAD

**Issue by Glockx** [krzysztofzablocki/Inject#11]
Hello,

Currently, I'm using Xcode 12 with Swift Tool Version 5.4, but the Inject's Swift Package is built with Swift Tool Version Is 5.5. So I cannot add this project to my application. Is it possible to add support for older Xcode versions (< Xcode 13)? 

Thanks in advance, have a nice and safe day.

**Comment by krzysztofzablocki** [comment]
It would work but I think you'd probably want to use older InjectionIII version that had unhide logic since we dropped it recently, right @johnno1962 ?

**Comment by johnno1962** [comment]
Yeah, but if you encounter an undefined default argument symbol it will fall back to going an unhide and suggest you restart the app. Should be no problem. I test it with Xcode 11!

**Comment by Glockx** [comment]
I guess InjectionIII is not related to the issue. Because SPM cannot add the package to the project. 

![Preview](https://i.imgur.com/9pUA6Wu.png)

**Comment by krzysztofzablocki** [comment]
@Glockx dropped down to 5.3, you should be good to go
