### ISSUE TITLE
Why `Hosts` are not available in non-DEBUG configs?

### ISSUE THREAD

**Issue by ms-int** [krzysztofzablocki/Inject#12]
Error occurs while compiling for config inheriting from Debug config. On Debug config works well.
![Zrzut ekranu 2022-04-6 o 11 40 01](https://user-images.githubusercontent.com/96171298/161946337-8af2e8a9-558e-45ea-b7ee-e6836846545b.png)
.

**Comment by krzysztofzablocki** [comment]
I strip those symbols if you don't define DEBUG so that they don't land in production application. 
This is by design since unlike SwiftUI integration hosts can't be true NO-OP and would incur some cost to your application (additional view layer etc).

**Comment by abdalaliii** [comment]
I believe XCode new projects have two default configurations, Debug and Release, and SPM works only with that two configurations. I believe if we change that configuration name when we import any SPM module XCode will show an error like this.

**Comment by wojciech-kulik** [comment]
Maybe we could add support for release code this way: #14
