### ISSUE TITLE
How to deal with non-standard Xcode location?

### ISSUE THREAD

**Issue by ptrkstr** [krzysztofzablocki/Inject#13]
A user may not have Xcode named `Xcode.app`.
A case in point is when [utilising the Xcodes.app to install Xcode](https://github.com/RobotsAndPencils/XcodesApp/issues/180). That appends the Xcode version to the name.
Using `DEVELOPER_DIR` makes the Xcode name agnostic.

**Comment by johnno1962** [comment]
This is unfortunate and InjectionIII.app may work if there isn't an Xcode at the normal path but I can't guarantee it. Using a symbolic link at /Applications/Xcode.app when you have multiple Xcodes installed is perfectly fine.

**Comment by gohanlon** [comment]
I setup Inject and InjectionIII.app yesterday with an Xcode installed via [Xcodes](https://github.com/RobotsAndPencils/xcodes), and I can confirm that a symlink is all that's needed:

``` zsh
% ln -s /Applications/Xcode-13.3.0.app /Applications/Xcode.app
```
