### ISSUE TITLE
Not updating in simulator

### ISSUE THREAD

**Issue by okla** [krzysztofzablocki/Inject#16]
I have a simple SwiftUI project (2 files), everything is installed and set up, I see all the messages from InjectionIII in console. But changes that I make in views do not appear in simulator.

**Comment by johnno1962** [comment]
What does the debug console say? Are you watching the correct directory? Did you add an injectionObserver?

**Comment by okla** [comment]
Yes, imported Inject, added Observer and called enableInjection(). Console shows correct messages, same as here https://github.com/krzysztofzablocki/Inject#individual-developer-setup-once-per-machine

**Comment by johnno1962** [comment]
Very difficult to say what the problem would be. Are you able to zip up the project and post it?

**Comment by johnno1962** [comment]
Have you added "Other Linker Flags" "-Xlinker -interposable"?

**Comment by okla** [comment]
Yes, flags are added. I will try to prepare a test project tomorrow.

**Comment by wojciech-kulik** [comment]
I had today the same problem when I switched from the InjectionIII app installed manually to InjectionIII installed from App Store. Not sure what was the problem. Files were recompiled correctly, but the view was not refreshing. I switched back to the previous version and it works again.

**Comment by johnno1962** [comment]
Interesting, this could be something to do with the defaults remembering the selected project. If in doubt, select the project directory again using menu item "Open Project". I'll have a look at the code.

**Comment by wojciech-kulik** [comment]
@johnno1962 I tried with "Open Project" and cleaned up settings, still doesn't work. I noticed this version works more slowly and produces this warning:
```
Class _TtC10MyModule39MyFile is implemented in both /MyApp/Smth (0x112eb1b58) and /private/var/folders/c3/fn8391xj715ccg2w6bcv8s8w0000gn/T/com.johnholdsworth.InjectionIII/eval101.dylib (0x194ec9010). One of the two will be used. Which one is undefined
```
I guess that's the problem because I debugged the app and it reloads the view, however it doesn't see changes.

**Comment by krzysztofzablocki** [comment]
It's better to use the github version of Injection app @wojciech-kulik because it's newest and @johnno1962 often cuts new updates as we extend the tool, appstore version has longer release cycle

**Comment by amadeuszpolak** [comment]
same problem here ... I have created a swiftUI testApp and it doesn't work.
<img width="563" alt="Screenshot 2022-04-08 at 09 25 44" src="https://user-images.githubusercontent.com/3585033/162386687-e44467f6-f2a7-4d2c-aa50-99b54e69425f.png">
<img width="783" alt="Screenshot 2022-04-08 at 09 26 13" src="https://user-images.githubusercontent.com/3585033/162386747-74409ee9-a388-4152-a453-1601361bd48c.png">

I got error about "-Xlinker -interposable" flags but as you can see on the SS it is added. Any advices ? I use the newest version of Xcode.

**Comment by krzysztofzablocki** [comment]
@amadeuszpolak does the [example app](https://github.com/MarcoEidinger/InjectSwiftUIExample) work for you?

**Comment by amadeuszpolak** [comment]
I have watched the video and the reason was that I added those flags to the Project and not to the target. Now it works ;) thanks guys !

**Comment by johnno1962** [comment]
Great news! @okla, could this be your problem?

**Comment by okla** [comment]
@johnno1962 Yep, that was the problem, everything works now!

**Comment by johnno1962** [comment]
Hurrah!
