### ISSUE TITLE
Is it possible to use with storyboards?

### ISSUE THREAD

**Issue by tylerjames** [krzysztofzablocki/Inject#19]
I've since switched to creating view controllers and UI programmatically, but I still have several VCs use storyboards. Is there any way to integrate Inject with views and VCs that are loaded this way?

thanks

**Comment by krzysztofzablocki** [comment]
It used to be that you just build project (not run) and it re-builds Storyboards / Nib's, but I've honestly not used it for years so not sure if it still works
