### ISSUE TITLE
Where should `@_exported import Inject` be placed?

### ISSUE THREAD

**Issue by chadparker** [krzysztofzablocki/Inject#21]
>You can either add import Inject in individual files in your project or use @_exported import Inject in your project target to have it automatically available in all its files.

Where should I add this line? Google didn't help me in this case.

(thank you for this great library!)

**Comment by krzysztofzablocki** [comment]
any file in your target will mean that you no longer need to import Inject into individual files

**Comment by chadparker** [comment]
Thank you!
