### ISSUE TITLE
Project Won't Build Because Of Lower iOS Version Support

### ISSUE THREAD

**Issue by Glockx** [krzysztofzablocki/Inject#27]
I guess the supported iOS version has lowered to iOS 11, but It won't build because SwiftUI and Combine support starts from iOS 13. 

![preview](https://i.imgur.com/0G7biY8.png)

**Comment by rehatkathuria** [comment]
Also seeing related compiler warnings in this file with `SwiftUI.View`

https://github.com/krzysztofzablocki/Inject/blob/main/Sources/Inject/Integrations/SwiftUI.swift

**Comment by krzysztofzablocki** [comment]
Haha my bad 😅 I'll add ifdef's in a bit

**Comment by krzysztofzablocki** [comment]
my bad, cutting stuff before coffee is a mistake
