### ISSUE TITLE
Doesn't work on Mac Catalyst

### ISSUE THREAD

**Issue by rrenna** [krzysztofzablocki/Inject#3]
I believe it's due to the logic dictated by:
`#if canImport(AppKit)`

As Catalyst can import AppKit but only for limited use, ie. NSToolbar.

NSView, etc are unavailable.

**Comment by rrenna** [comment]
Maybe just switch around the #if / #elseif order so Catalyst will trigger the `canImport(UIKit)` ?

**Comment by krzysztofzablocki** [comment]
Good call, I can do that tomorrow

**Comment by krzysztofzablocki** [comment]
fixed on main
