### ISSUE TITLE
Inject View Controller which conforms to protocol 

### ISSUE THREAD

**Issue by romaHerman** [krzysztofzablocki/Inject#38]
First Thanks for the great tool!!!

Here is my question: 
I have a view controller which conforms to protocol "MyProtocol" 
then I do `let calendar = Inject.ViewControllerHost(CalendarViewController())` 
and try to pass this calendar to the SideMenu which expects VC of MyProtocol type 
but calendar returns nil, when I do calendar as? MyProtocol 

are there any workarounds of this ?

**Comment by romaHerman** [comment]
unfortunately it didn't help

**Comment by johnno1962** [comment]
Any chance of a small example project so I could look into what's going on?

**Comment by romaHerman** [comment]
Yes 
Let me try to construct one

**Comment by romaHerman** [comment]
Here is a sample project 
https://github.com/romaHerman/InjectTest
It has TestComponents xCodeProject and main xCodeProject 
in SceneDelegate you can find test invocations of methods 

it's similar to my setup in main project

**Comment by johnno1962** [comment]
Thanks for the example project. Injection aside, I can see that `Inject.ViewControllerHost(CalendarViewController())` has type `Inject.ViewControllerHost<CalendarViewController>` not `CalendarViewController` which even though it is defined as a subclass of CalendarViewController does not acquire the conformance to `TestProtocol`. This seems to be a Swift thing. @krzysztofzablocki?

**Comment by johnno1962** [comment]
... I think you need to do something like:
```
        if let vc = vc.instance as? TestProtocol {
            vc.testPrint()
        }

**Comment by romaHerman** [comment]
Thanks! 

It does work in this case with vc.TestPrint() 

but unfortunately it won't solve problem with passing this view to side menu 

I have SideMenu which does `navigationController.pushViewcontroller(<VC>)` 
and in order Inject to work in should push `vc` not `vc.instance` 

problem is here 
```
let calendar = Inject.ViewControllerHost(CalendarViewController())
sideMenu.view = calendar.instance
```

**Comment by johnno1962** [comment]
How do you mean "for inject to work"? If you save the file containing CalendarViewController, its methods will have been overridden for the next time they are called again.

**Comment by romaHerman** [comment]
here is how I'm trying to do 

`let calendar = Inject.ViewControllerHost(CalendarViewController())
 viewControllers = [NewsViewController(), calendar.instance]
menu.viewcontrollers = viewControllers` 

inside menu viewControllers variable is declared like this 
`var viewControllers: [MenuProtocol] = []` 
and when I do 
`menu.selectedIndex = 1` 
inside it does following 
`navigationController.setViewcontrollers[viewControllers[selectedIndex]` 
so it sets calendar.instance not the calendar itself and I think this the problem why Inject doesn't hot reload it for me

**Comment by johnno1962** [comment]
It's possible the "Hosting" model Inject uses may not be for you in this instance. When you save the file containing NewsViewController it will have been "swizzled" correctly. Perhaps you just need a way to force it to redraw. Have you looked at creating an `@objc func injected()' method which should be called when the class is injected inside which you call viewDidLoad() or configure() or something to force the redraw so you can see the hot reload.

**Comment by romaHerman** [comment]
Thanks

I've overlooked this 
How I can do that ?

**Comment by johnno1962** [comment]
create an `@objc func injected()` function in your file and see if it gets called. If it does, then you can do some stuff in it.

**Comment by romaHerman** [comment]
Maybe I will have to change SideMenu somehow to accept viewControllers
injected doesn't get called

**Comment by johnno1962** [comment]
I can zoom if you get stuck.

**Comment by romaHerman** [comment]
wow, thanks a lot! 
if it works for you I'm ready 
Tell me when you have time for that

**Comment by johnno1962** [comment]
Or TeamView. Send an invite/login to github at johnholdsworth.com

**Comment by johnno1962** [comment]
Actually, TeamView if you can thanks.

**Comment by johnno1962** [comment]
You seem to be watching the workspace file instead of watching the directory containing the workspace file. Use menu item "Open Project" to set it again.

**Comment by krzysztofzablocki** [comment]
for passing specific type only `.instance` can work, but in that scenario I'd recommend probably not commiting host changes, I usually just do host swap in separate commit I can easily delete at the end of feature work
