### ISSUE TITLE
i couldn't  present ViewController

### ISSUE THREAD

**Issue by isGeekCode** [krzysztofzablocki/Inject#39]
at first, Thank you for make this comfortable method

What I want is simple
I want to make an "ViewController" that becomes "inject"

i wrote  below it

```
//no.1
       let viewController = Inject.ViewControllerHost(LoginViewController())
        self.navigationController?.pushViewController(viewController, animated: true)
//no.2
//        present(viewController, animated: true, completion: nil)

```

I'm sorry to ask you such an easy one

What should I do?

**Comment by krzysztofzablocki** [comment]
I'm unclear what your issue is, the code you posted should just work
