### ISSUE TITLE
Could not find module for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by VitaliiDeveloper** [krzysztofzablocki/Inject#42]
Hi all✌️
When I have SPM + Pods on mac m1 you get error:  `Could not find module for target 'x86_64-apple-ios-simulator'`
Then I setted `VALID_ARCHS = "arm64, x86_64"` and got errors for Inject lib.

Maybe somebody had the same issue and knows how to fix. 

Here Pods settings:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.pods_project.targets.each do |target|
    puts target.name
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
```

**Comment by VitaliiDeveloper** [comment]
The issue is in SPM because you can not Exclude arm64 for it... and only one way to use it it's run under Rosseta

**Comment by markst** [comment]
This issue is usually the case when SPM's include a XCFramework which doesn't include the appropriate architecture slice.

However this repo does not use a `XCFramework`. @VitaliiDeveloper are you sure the error is due to this package?
