### ISSUE TITLE
How to use it with .xib or .storyboard?

### ISSUE THREAD

**Issue by AndrewPetrov** [krzysztofzablocki/Inject#51]
I need to reload .xib or .storyboard to see an updated UI in my app. How can I use it in this way?
I see a message in the console

`Problem reloading nib: *** -[__NSDictionaryM setObject:forKeyedSubscript:]: key cannot be nil`

**Comment by krzysztofzablocki** [comment]
Xib / Storyboard injection support in Injection app is not really maintained anymore so that use-case is not supported
