### ISSUE TITLE
Incompatible with builds for Intel?

### ISSUE THREAD

**Issue by wojciech-kulik** [krzysztofzablocki/Inject#6]
```
Could not find module 'Inject' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator
```

Could you make it compatible with builds for Intel?

**Comment by krzysztofzablocki** [comment]
This project doesn't have any dependencies, nor does it define platform restrictions.

Are you using Catalyst? That's the only thing not supported atm (I'll add it tomorrow)

If not this is probably an issue on your project side?

**Comment by wojciech-kulik** [comment]
We run a simulator on Rosetta, because of compatibility issues and we build the project for x86_64. We don't use Catalyst.

I included the source code directly instead of using PM and it builds correctly then. Maybe it's something with PM.

**Comment by krzysztofzablocki** [comment]
@wojciech-kulik try tweaking either Build Active Architecture or Always Embeed Swift binaries settings :)
