### ISSUE TITLE
Debug View Hierarchy stops working after compiling a new ViewController

### ISSUE THREAD

**Issue by nunogoncalves** [krzysztofzablocki/Inject#60]
Hey Krzysztof. Thanks for the awesome tool!

I would like to ask if you have any known issues with Debug View Hierarchy (DVH). 
I can run the app and navigate to a screen that hosts my ViewController. If at first I debug the view hierarchy, it works ok. 
Now I update some code and hit save. Once it gets injected, DVH stops working, as in I tap the button and nothing happens. Once I make another save in the file then Xcode opens the DVH window on a loading state until I get this:

![image](https://user-images.githubusercontent.com/3007012/203986999-fe56e895-a0c8-4cdb-896b-b806cda3ddf6.png)

I'm not thinking this will break my workflow a lot but got curious to know if this is known and if there's any explanation for it. 

Thanks again for this awesome tool. You and obviously, @johnno1962 👌🏼 🙏🏼

**Comment by johnno1962** [comment]
I don't think I've ever used that feature. TBH, they won't appreciate it but this is more a radar sort of problem.
