### ISSUE TITLE
InjectionIII connected but view doesn't reload

### ISSUE THREAD

**Issue by Dominus666** [krzysztofzablocki/Inject#66]
**Hi, I have issue with hot-reload. In terminal I have next message**
//
💉 InjectionIII connected /Users/mac/Documents/Developer/Barter(swift)/Barter(swift).xcodeproj
💉 Watching files under the directory /Users/mac/Documents/Developer/Barter(swift)
//
 **and after when I press "ctrl + s" I have next message**
 //
 💉 Compiling /Users/mac/Documents/Developer/Barter(swift)/Barter(swift)/Views/AuthViews/AuthView.swift
💉 Loading .dylib ...
💉 Interposed 3 function references.
💉 Injected type #1 'Barter_swift_.AuthView'
💉 Injected type #2 'Barter_swift_.AuthView_Previews'
//

**but simulator doesn't reload**

**Comment by johnno1962** [comment]
Hi, do you have an instance variable in your View initialised to the `Inject.observer` or an `@ObserveInject` variable to force the redraw?

**Comment by Dominus666** [comment]
> Hi, do you have an instance variable in your View initialised to the `Inject.observer` or an `@ObserveInject` variable to force the redraw?

did you mean this?
<img width="432" alt="Screenshot 2023-01-25 at 10 12 01" src="https://user-images.githubusercontent.com/38140505/214512082-0fc3ec12-5a9a-49ce-bf7e-4414ff53a0e2.png">

**Comment by johnno1962** [comment]
Yes, @ObserveInjection, sorry. And it's still not redrawing? Do you have an @ObserveInjection in the Layout() view? They don't cascade unfortunately.

**Comment by Dominus666** [comment]
I use only one @ObserveInjection

**Comment by Dominus666** [comment]
it's redrawing only in view where I add @ObserveInjection

**Comment by johnno1962** [comment]
Only views that contain an @ObserveInjection are redrawn automatically. The subview appearance is cached by SwiftUI unless you add a @ObserveInjection to the subview which lets it know if needs to redraw.

**Comment by Dominus666** [comment]
ok, hank you, it's working.
and when I add @observe, should I rebuild project?
because I get error

**Comment by johnno1962** [comment]
Sorry by @ObserveInject, I meant @ObserveInjection.

**Comment by Dominus666** [comment]
ty for the help
