### ISSUE TITLE
SwiftUI + UIKit project causes crashes

### ISSUE THREAD

**Issue by naturecodevoid** [krzysztofzablocki/Inject#70]
Hi, we have a UIKit project that we are currently working on migrating to SwiftUI. The default view is SwiftUI, and we use a `UIHostingController` to display it. I’ve added inject into the SwiftUI view, and editing already added elements works fine (like changing text). However, if I add a new element, it crashes the app with `Thread 1: EXC_BAD_ACCESS (code=1, address=…)`. Is there any way I can fix this? I’ve tried using `Inject.ViewControllerHost` on the `UIHostingController`, and also using `Inject.ViewControllerHost` without having inject in the SwiftUI part, but neither helped.

Our project is open source, and I can give you a link to the branch with the SwiftUI stuff if needed. (I haven’t pushed adding Inject yet.) It’s a pretty complex project, and uses libraries written in Objective-C and Rust, so it might take a little while to setup.

**Comment by johnno1962** [comment]
Hi, Can you post an image of the stack trace or the link to the branch please?

**Comment by naturecodevoid** [comment]
Here’s the branch: https://github.com/SideStore/SideStore/tree/naturecodevoid/swiftui-improvements
As I said, it is a decently complex project and setup might take a while. There are some compilation instructions: https://github.com/SideStore/SideStore/tree/naturecodevoid/swiftui-improvements#compilation-instructions
I will push adding inject now.

**Comment by johnno1962** [comment]
Your problem is probably because you are not calling .eraseToAnyView() at the end of your SwiftUI property method. You need to do this if you are going to add or remove elements to the View over an injection as it changes the concrete type of the `some View` which the containing view won't be expecting and will crash. You need to do this ahead of time for any view you want to be able to inject. There is more information about this in the https://github.com/johnno1962/HotSwiftUI Swift Package or in the README https://github.com/johnno1962/InjectionIII#swiftui-injection

**Comment by naturecodevoid** [comment]
Doesn't Inject already do this? https://github.com/krzysztofzablocki/Inject/blob/main/Sources/Inject/Integrations/SwiftUI.swift#L12

**Comment by johnno1962** [comment]
Inject contains an implementation of .eraseToAnyView() but it needs to be used part of your SwiftUI view implementation. Have a look at https://github.com/johnno1962/SwiftUI-Kit/blob/master/Shared/ContentView.swift for example.

**Comment by naturecodevoid** [comment]
https://github.com/SideStore/SideStore/blob/naturecodevoid/swiftui-improvements/AltStore/Views/RootView.swift#L32

I'm calling enableInjection, do I need to be doing something else?

**Comment by johnno1962** [comment]
Unfortunately you can't just do it at the top level. You need to add it to each component you want to be injectable.

**Comment by naturecodevoid** [comment]
I see. If I want it on one view, do I need to add it to all child view/components?

**Comment by johnno1962** [comment]
Just the view(s) you want to iterate over.

**Comment by naturecodevoid** [comment]
Ok, thanks! Do I also need to add the observer to every view, or just the root?

**Comment by naturecodevoid** [comment]
I'll close this now, tysm for the help!

**Comment by johnno1962** [comment]
NP. You need and injectionObserver per view you want to auto-redraw.
