### ISSUE TITLE
Interface Builder and prepare for segue

### ISSUE THREAD

**Issue by priore** [krzysztofzablocki/Inject#71]
Hello I have a question,
how can i use it in the following case?

thanks

<img width="1174" alt="Screenshot" src="https://user-images.githubusercontent.com/1537350/220997094-ec09f8cf-a48f-4d5a-ab1f-e9df4032c6cb.png">

**Comment by krzysztofzablocki** [comment]
this wouldn't work correctly, the instantiation needs to be autoclosure wrapped, passing in actual variable doesn't really do anything

**Comment by priore** [comment]
so it can't use with projects that use Interface Builder, right ?

**Comment by krzysztofzablocki** [comment]
You can just not on those vc's

**Comment by priore** [comment]
ok thanks
