### ISSUE TITLE
Could not find module for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by agisilaos** [krzysztofzablocki/Inject#74]
Hello there, I would love to integrate Inject into my project but as I follow the steps to do so, when I try to run the project using a simulator I get this error. I'm using Xcode 14.3. Not exactly sure what am I missing but any help would be greatly appreciated. 

`Could not find module for target 'x86_64-apple-ios-simulator'`

Excluded architectures in the project look like this:

<img width="468" alt="Screenshot 2023-04-28 at 15 44 59" src="https://user-images.githubusercontent.com/10944108/235150975-a44ddaa0-09e2-499f-a024-250dbdcc441b.png">

**Comment by johnno1962** [comment]
Hi, Is this an Intel or ARM Mac? What version of iOS are you simulating for?

**Comment by agisilaos** [comment]
@johnno1962 This is an M1 Mac and I'm tried to use both iOS 16.4 and 16.2!

**Comment by johnno1962** [comment]
Seeing arm64 excluded is a bit fishy. Are you sure your architectures are set to "Standard Architectures" and removed any "Excluded Architectures" (unless it is necessary for your build)?

**Comment by agisilaos** [comment]
@johnno1962 Architectures Look like this: 

<img width="986" alt="Screenshot 2023-04-28 at 16 09 11" src="https://user-images.githubusercontent.com/10944108/235156166-e7da3f36-7673-4182-b8a5-b716f11820bc.png">

**Comment by johnno1962** [comment]
So, you have a project that build and runs but when you add the Inject project it no longer does? That seems very unusual as Inject itself is relatively straightforward. I'm not sure there is much more help I can provide without being at your desk, this seems to be a more general Xcode question.

**Comment by agisilaos** [comment]
> So, you have a project that build and runs but when you add the Inject project it no longer does

That's exactly the situation...

**Comment by johnno1962** [comment]
It's more likely to be specific to your project than specific to the Inject Swift Package. Have you tried with something simpler as a starting point?

**Comment by agisilaos** [comment]
I tried with a new project and it works just fine, this is kind of confusing tbh with you.


 I also tried using a device and that works, but then I tried to "track" the project using Injection and it won't track the project. It's a monorepo using xcworkspace

**Comment by johnno1962** [comment]
Yeah, It's just an Xcode bug. How do you mean "track". Do you mean "trace"?

**Comment by agisilaos** [comment]
@johnno1962 Sorry for the delay on this. I meant trace yes. It doesn't seem to work. I may need to investigate that a bit more and open a fresh issue. Thank you so much for your help already.

**Comment by johnno1962** [comment]
What do you want to trace and how are you trying to do it? It's not a massively requested or supported part of the application as it is technically quite challenging.
