### ISSUE TITLE
Please update "-Xlinker -interposable" instruction.

### ISSUE THREAD

**Issue by Samback** [krzysztofzablocki/Inject#80]
@krzysztofzablocki first of all BIG thanks for your library! One issue I faced during integration was a misunderstanding with adding '-Xlinker -interposable' in the config. I believe it would be helpful for everyone to avoid the mistake I made. Note that these flags should be separated and added independently.

```html
-Xlinker
-interposable
``` 

Regards,
Max

**Comment by johnno1962** [comment]
Hi, Yes, this is a new feature of Xcode 15 where it makes a point of quoting these options together and the linker due to how it parses the options doesn't give you a error or warning. I had to tweak the InjectionII README for this:
```
It's also important to add "-Xlinker -interposable" (without the double quotes and on separate lines)

**Comment by Samback** [comment]
@johnno1962 
It took me a couple of hours to realize where the mistake was because I was implementing Inject for the first time. It felt like a bad joke when I followed all the steps correctly, and it didn't work, but it works perfectly on the demo app.

**Comment by johnno1962** [comment]
Perhaps you could contribute a PR with some revised wording?

**Comment by krzysztofzablocki** [comment]
updated
