### ISSUE TITLE
TCA 1.7.3 crash (ComposableArchitecture/Store.swift:682: Fatal error: Unexpectedly found nil while unwrapping an Optional value)

### ISSUE THREAD

**Issue by kuglee** [krzysztofzablocki/Inject#87]
I'm trying to use this package with TCA 1.7.3, however when a non-leaf view is changed the app crashes. I've created an example project for this: [InjectTCATest](https://github.com/kuglee/InjectTCATest).
In the linked project if I change the `Text("AppFeature")` in `AppView` to `Text("AppFeature2")` there's a crash:
```
💉 InjectionIII connected /Users/kuglee/Downloads/InjectTCATest/InjectTCATest.xcodeproj
💉 Watching files under the directory /Users/kuglee/Downloads/InjectTCATest
💉 Compiling /Users/kuglee/Downloads/InjectTCATest/InjectTCATest/AppFeature.swift
💉 Selecting Xcode /Applications/Xcode-beta.app/Contents/Developer
💉 Loading .dylib ...
💉 Interposed 15 function references.
💉 Injected type #1 'InjectTCATest.AppFeature'
💉 Injected type #2 'InjectTCATest.AppFeature.State'
💉 Injected type #3 'InjectTCATest.AppFeature.Action'
💉 Injected type #4 'InjectTCATest.AppFeature.Action.AllCasePaths'
💉 Injected type #5 'InjectTCATest.AppView'
ComposableArchitecture/Store.swift:682: Fatal error: Unexpectedly found nil while unwrapping an Optional value
```
<img width="1680" alt="crash" src="https://github.com/krzysztofzablocki/Inject/assets/1316211/373bf3f4-d306-4fbd-9298-771e4ddab0d0">

If I change the `Text("ChildFeature")` in `ChildView` to `Text("ChildFeature2")` it works as expected.

**Comment by johnno1962** [comment]
Hi, a top level variable could be getting reinitialised on injection. Can you try setting an environment variable in your scheme: INJECTION_PRESERVE_STATICS ? Any value will do.

**Comment by kuglee** [comment]
I've set the environment variable. Unfortunately the same crash still occurs.
![ INJECTION_PRESERVE_STATICS](https://github.com/krzysztofzablocki/Inject/assets/1316211/ec558763-caed-40ab-8cfe-3ca6f9aa2ff3)

**Comment by johnno1962** [comment]
I'm afraid I can't tell you why but if you move the AppFeature struct into the ChildFeature.swift file things work. It's better to have types in their own files with injection.

**Comment by krzysztofzablocki** [comment]
Yeah that's my experience too, try to keep type per file and not multiple related types in single file, maybe something to do with order of pathing @johnno1962 ?

**Comment by johnno1962** [comment]
Patching? If you move the types around in the file it doesn't seem to help. These are suddenly complicated files with all the macros that are creating static member variables so it's not clear what's going on. It's a shame but the first thing to try when you get this type of crash is separating out/moving around the types.

**Comment by johnno1962** [comment]
Thanks @kuglee for your example project. It makes very clear what the problem was which is that the "key path accessor functions" get injected and therefore the key path isn't recognised as being the same inside the TCA code resulting in the force unwrap 😱 failing. For now, I can't get "reverse interposing" which would be a solution for this working so it's _not possible to inject a type the fields of which are referenced using key paths_ i.e you can't inject a file containing the AppFeature struct.

**Comment by kuglee** [comment]
That's a bummer. Anyway, thank you for looking into this.

**Comment by johnno1962** [comment]
@kuglee, I may have found a solution of sorts for this problem if you want to try the new release candidate https://github.com/johnno1962/InjectionIII/releases/tag/4.8.4RC3
The fix is enabled if you set an INJECTION_KEYPATHS environment variable in your scheme. Thanks for creating the test project. It was a great help working out where the problem was.

**Comment by kuglee** [comment]
If I set the INJECTION_KEYPATHS, I have the following crash:
<img width="1680" alt="xcode" src="https://github.com/krzysztofzablocki/Inject/assets/1316211/fb2152d9-bc4a-4b84-b25e-585b49b1bb7e">
![shceme](https://github.com/krzysztofzablocki/Inject/assets/1316211/3e7e7359-3948-4273-844f-e0781eddda02)

**Comment by johnno1962** [comment]
Thanks for trying it out so quickly. Which version of Xcode is this and which build number of the InjectionIII.app? (It's in the Info.plist - it should be 8012)

**Comment by kuglee** [comment]
Xcode: Version 15.3 (15E204a)
InjectionIII: 4.8.4

**Comment by kuglee** [comment]
InjectionIII: 8012

**Comment by johnno1962** [comment]
I've uploaded a new 4.8.4 release candidate, this time build 8014. Can you give it a try? There was an iOS specific problem.

**Comment by kuglee** [comment]
I've tried 8014. The original issue still occurs:
<img width="1680" alt="xcode" src="https://github.com/krzysztofzablocki/Inject/assets/1316211/c5f53ea5-e3e2-43ad-9159-fb1038597a27">

**Comment by johnno1962** [comment]
Disappointing. And the env var was set? What are you trying to do? Start with just saving the AppFeature.swift file and work you way up from there to see what is possible now.

**Comment by kuglee** [comment]
I've pushed an update to the sample project with the environment variables.

 I've changed the Text("AppFeature") in AppView to Text("AppFeature2") just like in the first example when the crash occurred.

**Comment by johnno1962** [comment]
OK, I've updated the RC to build 8015. The iOS specific problem was more involved than I thought. Can you give it a try please? You should see a message `💉 Recycling ...` if it is working.

**Comment by kuglee** [comment]
It works now for iOS and also macOS!
Thanks for taking the time 🙏

**Comment by johnno1962** [comment]
Great! Yes, this one was a real time consumer but having the Feature and View in the same file is the norm for TCA so I really wanted to be sure it worked even if people have to remember to opt into the env var for now. There will be limits and if you run up against something let me know. If you don't remember there is a tip jar on the InjectionIII project!
