### ISSUE TITLE
Module 'Inject' has no member named 'ViewControllerHost'

### ISSUE THREAD

**Issue by RodrigoIbarraSanchez** [krzysztofzablocki/Inject#94]
I'm using this version:
`{
      "identity" : "inject",
      "kind" : "remoteSourceControl",
      "location" : "https://github.com/krzysztofzablocki/Inject.git",
      "state" : {
        "branch" : "main",
        "revision" : "838e614220000a563bbaeba2974236f2c2c51e13"
      }
 }`
    
but having errors using `Inject.ViewControllerHost()` and .never

Errors:
Module 'Inject' has no member named 'ViewControllerHost'
Cannot infer contextual base in reference to member 'never'

Any thoughts on why this happens on newer versions?

**Comment by RodrigoIbarraSanchez** [comment]
I'm not having issues using the previous revision `e91205e809f7bd7f6fc3f26fc0b5c1fbfaac20c6`.

**Comment by krzysztofzablocki** [comment]
It was renamed for framework use, so just update your references

**Comment by krzysztofzablocki** [comment]
It used to be under namespace, it is now not, it's just called ViewControllerHost or ViewHost

**Comment by RodrigoIbarraSanchez** [comment]
> e91205e809f7bd7f6fc3f26fc0b5c1fbfaac20c6

what do you mean by "update your references"? I still using e91205e809f7bd7f6fc3f26fc0b5c1fbfaac20c6 version to avoid the issue. Regards.

**Comment by krzysztofzablocki** [comment]
just change the name in your codebase and use newest inject
